import '../css/app.css';
import './bootstrap';

import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/vue3';

/**
 * Penova Core — Inertia entry point.
 *
 * Page components resolve from two roots:
 *   Core/...            → resources/js/Core/Pages/...   (Core's own, glob-resolved)
 *   Modules/<Name>/...  → ONLY through the generated module-frontend registry: a
 *                         Module page must be declared as a typed `frontend` entry
 *                         in its Manifest. Core keeps NO module-directory glob and
 *                         NO render-path convention — a page name with no registry
 *                         entry fails loudly.
 *
 * EXPERIMENTAL SEAM — the module-frontend seam is experimental (RFC-006 / D-028):
 * it is conspicuously labelled and may change or be withdrawn WITHOUT a MAJOR until
 * a second independent Module graduates it. It is NOT yet under the stability
 * promise. `app/Modules/README.md` is the primary seam doc for Module authors.
 *
 * The registry (`./generated/module-frontend-registry.js`) is a git-ignored build
 * artifact, regenerated by `php artisan penova:frontend-registry` before every
 * build. Core names no Module here — the map is registry output.
 */
import { modulePages } from './generated/module-frontend-registry.js';

const corePages = import.meta.glob('./Core/Pages/**/*.vue');

createInertiaApp({
    title: (title) => (title ? `${title} — Penova` : 'Penova'),

    resolve: (name) => {
        if (name.startsWith('Modules/')) {
            const page = modulePages[name];
            if (!page) {
                throw new Error(
                    `Penova: no module-frontend registry entry for page [${name}]. ` +
                        'Declare it in the Module Manifest `frontend` section and regenerate: ' +
                        'php artisan penova:frontend-registry',
                );
            }
            return page();
        }

        // "Core/Users/Index" → ./Core/Pages/Users/Index.vue
        return corePages[`./Core/Pages/${name.replace(/^Core\//, '')}.vue`]();
    },

    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .mount(el);
    },
});
